import { PrismaClient } from "@prisma/client";

const BUILDERS = [
  { name: "Lodha Group", company: "Lodha Group Ltd", email: "info@lodhagroup.com", phone: "022-61313636", city: "Mumbai", gstNumber: "27AAACL1234A1Z5" },
  { name: "Prestige Estates", company: "Prestige Estates Projects Ltd", email: "sales@prestigeconstructions.com", phone: "080-25591080", city: "Bangalore", gstNumber: "29AABCP1234B1Z8" },
  { name: "EstatePro Developers", company: "EstatePro Realty Pvt Ltd", email: "builders@estatepro.com", phone: "022-40001234", city: "Mumbai", gstNumber: "27AABCE1234C1Z2" },
];

const PROJECTS = [
  {
    slug: "lodha-mirabelle",
    name: "Lodha Mirabelle",
    description: "Ultra-luxury 2, 3 & 4 BHK apartments in Parel with panoramic city views, clubhouse, and sky lounge.",
    location: "Parel",
    city: "Mumbai",
    developer: "Lodha Group",
    builderName: "Lodha Group",
    status: "UNDER_CONSTRUCTION" as const,
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&h=520&fit=crop",
    totalUnits: 280,
    priceFrom: 21000000,
    priceTo: 45000000,
    featured: true,
  },
  {
    slug: "skyline-residences",
    name: "Skyline Residences",
    description: "Premium sea-facing apartments in Bandra West with world-class amenities.",
    location: "Bandra West",
    city: "Mumbai",
    developer: "EstatePro Developers",
    builderName: "EstatePro Developers",
    status: "UNDER_CONSTRUCTION" as const,
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&h=520&fit=crop",
    totalUnits: 120,
    priceFrom: 8500000,
    priceTo: 25000000,
    featured: true,
  },
  {
    slug: "green-valley-villas",
    name: "Green Valley Villas",
    description: "Spacious 3 & 4 BHK villas in Whitefield with private gardens and community pool.",
    location: "Whitefield",
    city: "Bangalore",
    developer: "Prestige Estates",
    builderName: "Prestige Estates",
    status: "READY_TO_MOVE" as const,
    image: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&h=520&fit=crop",
    totalUnits: 45,
    priceFrom: 12000000,
    priceTo: 35000000,
    featured: true,
  },
  {
    slug: "marina-bay-towers",
    name: "Marina Bay Towers",
    description: "Iconic twin towers on Marine Drive offering unobstructed Arabian Sea views.",
    location: "Marine Drive",
    city: "Mumbai",
    developer: "Lodha Group",
    builderName: "Lodha Group",
    status: "PLANNING" as const,
    image: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&h=520&fit=crop",
    totalUnits: 200,
    priceFrom: 15000000,
    priceTo: 50000000,
    featured: true,
  },
  {
    slug: "prestige-lakeside",
    name: "Prestige Lakeside Habitat",
    description: "Lake-view apartments in Hinjewadi IT corridor with metro connectivity.",
    location: "Hinjewadi",
    city: "Pune",
    developer: "Prestige Estates",
    builderName: "Prestige Estates",
    status: "UNDER_CONSTRUCTION" as const,
    image: "https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=800&h=520&fit=crop",
    totalUnits: 350,
    priceFrom: 5500000,
    priceTo: 12000000,
    featured: true,
  },
  {
    slug: "emerald-heights",
    name: "Emerald Heights",
    description: "Premium gated community in Gurgaon Sector 62 with 2 & 3 BHK smart homes.",
    location: "Sector 62",
    city: "Gurgaon",
    developer: "EstatePro Developers",
    builderName: "EstatePro Developers",
    status: "UNDER_CONSTRUCTION" as const,
    image: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=520&fit=crop",
    totalUnits: 180,
    priceFrom: 7500000,
    priceTo: 14000000,
    featured: true,
  },
];

const LAUNCHES = [
  {
    slug: "ocean-view-prelaunch",
    name: "Ocean View Residences",
    description: "Exclusive pre-launch in Juhu with early-bird pricing and flexible payment plan.",
    location: "Juhu",
    city: "Mumbai",
    status: "UPCOMING" as const,
    launchDate: new Date("2026-07-15"),
    image: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&h=520&fit=crop",
    priceFrom: 9500000,
    priceTo: 18000000,
    featured: true,
    projectSlug: "marina-bay-towers",
  },
  {
    slug: "emerald-heights-phase2",
    name: "Emerald Heights Phase 2",
    description: "Phase 2 now live with limited inventory and 5% launch discount.",
    location: "Sector 62",
    city: "Gurgaon",
    status: "LIVE" as const,
    launchDate: new Date("2026-06-01"),
    image: "https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=800&h=520&fit=crop",
    priceFrom: 7500000,
    priceTo: 14000000,
    featured: true,
    projectSlug: "emerald-heights",
  },
  {
    slug: "royal-gardens-pune",
    name: "Royal Gardens",
    description: "Luxury villas in Pune with landscaped gardens and private terrace.",
    location: "Hinjewadi",
    city: "Pune",
    status: "UPCOMING" as const,
    launchDate: new Date("2026-08-20"),
    image: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=520&fit=crop",
    priceFrom: 5500000,
    priceTo: 12000000,
    featured: true,
    projectSlug: "prestige-lakeside",
  },
  {
    slug: "lodha-altamount",
    name: "Lodha Altamount",
    description: "Ultra-premium residences on Altamount Road — Mumbai's most prestigious address.",
    location: "Altamount Road",
    city: "Mumbai",
    status: "LIVE" as const,
    launchDate: new Date("2026-05-10"),
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=520&fit=crop",
    priceFrom: 35000000,
    priceTo: 85000000,
    featured: true,
    projectSlug: "lodha-mirabelle",
  },
  {
    slug: "prestige-city-phase3",
    name: "Prestige City Phase 3",
    description: "Integrated township launch in Bangalore with schools, hospital & retail.",
    location: "Sarjapur Road",
    city: "Bangalore",
    status: "UPCOMING" as const,
    launchDate: new Date("2026-09-01"),
    image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=520&fit=crop",
    priceFrom: 6800000,
    priceTo: 15500000,
    featured: true,
    projectSlug: "green-valley-villas",
  },
];

const PROPERTIES = [
  {
    slug: "luxury-3bhk-bandra",
    title: "Luxury 3 BHK Sea View Apartment",
    description: "Fully furnished 3 BHK with sea view, modular kitchen, and 2 covered parking.",
    address: "Bandra West, Linking Road",
    city: "Mumbai",
    price: 28500000,
    type: "APARTMENT" as const,
    bedrooms: 3,
    bathrooms: 3,
    sqft: 1650,
    image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=520&fit=crop",
    featured: true,
    projectSlug: "skyline-residences",
  },
  {
    slug: "premium-penthouse-juhu",
    title: "Premium Penthouse with Terrace",
    description: "Duplex penthouse with private terrace, jacuzzi, and 360° city views.",
    address: "Juhu Tara Road",
    city: "Mumbai",
    price: 52000000,
    type: "PENTHOUSE" as const,
    bedrooms: 4,
    bathrooms: 4,
    sqft: 3200,
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=520&fit=crop",
    featured: true,
    projectSlug: "lodha-mirabelle",
  },
  {
    slug: "modern-villa-whitefield",
    title: "Modern 4 BHK Villa with Garden",
    description: "Independent villa with landscaped garden, home theatre, and smart automation.",
    address: "Whitefield Main Road",
    city: "Bangalore",
    price: 18500000,
    type: "VILLA" as const,
    bedrooms: 4,
    bathrooms: 4,
    sqft: 2800,
    image: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&h=520&fit=crop",
    featured: true,
    projectSlug: "green-valley-villas",
  },
  {
    slug: "spacious-2bhk-hinjewadi",
    title: "Spacious 2 BHK Near IT Park",
    description: "Ready-to-move 2 BHK with clubhouse, gym, and swimming pool access.",
    address: "Hinjewadi Phase 1",
    city: "Pune",
    price: 7200000,
    type: "APARTMENT" as const,
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1100,
    image: "https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=800&h=520&fit=crop",
    featured: true,
    projectSlug: "prestige-lakeside",
  },
  {
    slug: "golf-course-villa-gurgaon",
    title: "Golf Course Facing Villa",
    description: "5 BHK villa overlooking golf course with private pool and servant quarter.",
    address: "DLF Golf Links, Sector 42",
    city: "Gurgaon",
    price: 45000000,
    type: "VILLA" as const,
    bedrooms: 5,
    bathrooms: 5,
    sqft: 4500,
    image: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&h=520&fit=crop",
    featured: true,
    projectSlug: "emerald-heights",
  },
  {
    slug: "corner-3bhk-marine-drive",
    title: "Corner 3 BHK Marine Drive",
    description: "Rare corner unit with wrap-around balconies and premium Italian marble flooring.",
    address: "Marine Drive",
    city: "Mumbai",
    price: 38000000,
    type: "APARTMENT" as const,
    bedrooms: 3,
    bathrooms: 3,
    sqft: 1850,
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&h=520&fit=crop",
    featured: true,
    projectSlug: "marina-bay-towers",
  },
  {
    slug: "studio-apartment-andheri",
    title: "Studio Apartment — Investment Ready",
    description: "Compact studio near metro, ideal for rental income. No brokerage.",
    address: "Andheri East, MIDC",
    city: "Mumbai",
    price: 4500000,
    type: "APARTMENT" as const,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 450,
    image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=520&fit=crop",
    featured: false,
    projectSlug: "skyline-residences",
  },
  {
    slug: "commercial-space-bkc",
    title: "Premium Commercial Office Space",
    description: "Grade-A office space in BKC with 24/7 security and dedicated parking.",
    address: "Bandra Kurla Complex",
    city: "Mumbai",
    price: 62000000,
    type: "COMMERCIAL" as const,
    bedrooms: 0,
    bathrooms: 2,
    sqft: 3500,
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=520&fit=crop",
    featured: true,
    projectSlug: "lodha-mirabelle",
  },
];

export async function seedWebsite(prisma: PrismaClient, agentId: string) {
  const builderMap: Record<string, string> = {};

  for (const b of BUILDERS) {
    const existing = await prisma.builder.findFirst({ where: { name: b.name } });
    const builder = existing ?? await prisma.builder.create({ data: b });
    builderMap[b.name] = builder.id;
  }

  const projectMap: Record<string, string> = {};

  for (const p of PROJECTS) {
    const project = await prisma.project.upsert({
      where: { slug: p.slug },
      update: {
        name: p.name,
        description: p.description,
        location: p.location,
        city: p.city,
        developer: p.developer,
        builderId: builderMap[p.builderName],
        status: p.status,
        image: p.image,
        totalUnits: p.totalUnits,
        priceFrom: p.priceFrom,
        priceTo: p.priceTo,
        featured: p.featured,
      },
      create: {
        slug: p.slug,
        name: p.name,
        description: p.description,
        location: p.location,
        city: p.city,
        developer: p.developer,
        builderId: builderMap[p.builderName],
        status: p.status,
        image: p.image,
        totalUnits: p.totalUnits,
        priceFrom: p.priceFrom,
        priceTo: p.priceTo,
        featured: p.featured,
      },
    });
    projectMap[p.slug] = project.id;
  }

  for (const l of LAUNCHES) {
    await prisma.launch.upsert({
      where: { slug: l.slug },
      update: {
        name: l.name,
        description: l.description,
        location: l.location,
        city: l.city,
        status: l.status,
        launchDate: l.launchDate,
        image: l.image,
        priceFrom: l.priceFrom,
        priceTo: l.priceTo,
        featured: l.featured,
        projectId: l.projectSlug ? projectMap[l.projectSlug] : null,
      },
      create: {
        slug: l.slug,
        name: l.name,
        description: l.description,
        location: l.location,
        city: l.city,
        status: l.status,
        launchDate: l.launchDate,
        image: l.image,
        priceFrom: l.priceFrom,
        priceTo: l.priceTo,
        featured: l.featured,
        projectId: l.projectSlug ? projectMap[l.projectSlug] : null,
      },
    });
  }

  const properties = [];
  for (const p of PROPERTIES) {
    const property = await prisma.property.upsert({
      where: { slug: p.slug },
      update: {
        title: p.title,
        description: p.description,
        address: p.address,
        city: p.city,
        price: p.price,
        type: p.type,
        status: "FOR_SALE",
        bedrooms: p.bedrooms,
        bathrooms: p.bathrooms,
        sqft: p.sqft,
        image: p.image,
        featured: p.featured,
        projectId: projectMap[p.projectSlug],
        agentId,
      },
      create: {
        slug: p.slug,
        title: p.title,
        description: p.description,
        address: p.address,
        city: p.city,
        price: p.price,
        type: p.type,
        status: "FOR_SALE",
        bedrooms: p.bedrooms,
        bathrooms: p.bathrooms,
        sqft: p.sqft,
        image: p.image,
        featured: p.featured,
        projectId: projectMap[p.projectSlug],
        agentId,
      },
    });
    properties.push(property);
  }

  const skylineProject = await prisma.project.findUnique({ where: { slug: "skyline-residences" } });
  return { skylineProject: skylineProject!, properties, projectMap };
}
